<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>probe_cpu</AssemblyName>
    <Nullable>disable</Nullable>
    <NoWarn>CA2252</NoWarn>
  </PropertyGroup>
</Project>
