<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Awake.WorldbookStudio.BatchTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Awake.WorldbookStudio.Core\Awake.WorldbookStudio.Core.csproj" />
  </ItemGroup>
</Project>
