param([string]$ProjectRoot = (Split-Path $PSScriptRoot -Parent))
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Assert([bool]$condition,[string]$message){if(-not $condition){throw "FAIL PersonaEvidencePointerTests: $message"}}
function Hash([string]$path){(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToUpperInvariant()}
$temp=Join-Path $env:TEMP ('pwb-evidence-fixture-'+[guid]::NewGuid().ToString('N'));$artifact=Join-Path $temp 'artifacts';New-Item -ItemType Directory -Force -Path $artifact|Out-Null
try {
    $evidenceSource=Join-Path $ProjectRoot 'tools\ai-link-evidence-k1a-20260830.json';$captureSource=Join-Path $ProjectRoot 'tools\pretest-capture-k1a-20260830-run2.jsonl';$candidate=Join-Path $artifact 'candidate.json';$baseline=Join-Path $artifact 'k1a-old.json';$capture=Join-Path $artifact 'candidate.jsonl';$baselineCapture=Join-Path $artifact 'baseline.jsonl';Copy-Item $evidenceSource $candidate;Copy-Item $evidenceSource $baseline;Copy-Item $captureSource $capture;Copy-Item $captureSource $baselineCapture;$oldBaselineHash=Hash $baseline;$finalizer=Join-Path $ProjectRoot 'tools\finalize-ai-link-evidence.ps1'
    & $finalizer -WorkspaceRoot $temp -EvidencePath $candidate -BaselineEvidencePath $baseline -RequestCapturePath $capture -BaselineRequestCapturePath $baselineCapture -SessionFence 1 -ExpectedCurrentHash NONE -ErrorAction Stop|Out-Null
    $pointer=Get-Content -LiteralPath (Join-Path $artifact 'CURRENT-evidence.json') -Raw|ConvertFrom-Json -Depth 20;$sidecars=@(Get-ChildItem -LiteralPath $artifact -Filter 'supersession-*.json');Assert ($pointer.status -eq 'PASS') 'current pointer must be PASS';Assert ($sidecars.Count -eq 1) 'first finalization must create one supersession sidecar';Assert ((Hash $baseline) -eq $oldBaselineHash) 'old K1A evidence must remain byte immutable';$pointerHash=Hash (Join-Path $artifact 'CURRENT-evidence.json')
    $conflictSidecar=Join-Path $artifact 'supersession-conflict.json';$conflicted=$false;try{& $finalizer -WorkspaceRoot $temp -EvidencePath $candidate -BaselineEvidencePath $baseline -RequestCapturePath $capture -BaselineRequestCapturePath $baselineCapture -SessionFence 2 -ExpectedCurrentHash NONE -SupersessionPath $conflictSidecar -ErrorAction Stop|Out-Null}catch{$conflicted=$true};Assert $conflicted 'stale expectedCurrentHash must conflict';Assert ((Hash (Join-Path $artifact 'CURRENT-evidence.json')) -eq $pointerHash) 'pointer conflict must preserve old pointer';Assert (Test-Path -LiteralPath $conflictSidecar -PathType Leaf) 'pointer conflict must preserve new sidecar';Write-Output 'PASS PersonaEvidencePointerTests'
} finally {$resolved=(Resolve-Path -LiteralPath $temp).Path;if($resolved -like "$env:TEMP*"){Remove-Item -LiteralPath $resolved -Recurse -Force}}
