namespace Awake;

/// <summary>
/// 画位探测用的内置占位图：212x360，与 07 稿画位同尺寸。
/// 由 tools/make_portrait_probe_fixture.py 生成，别手改。
/// 用途只有一个——**在没有出图后端的情况下，把「png → 纹理 → 上屏」这条链证死**。
/// </summary>
internal static class AwakePortraitProbeFixture
{
    internal const int Width = 212;
    internal const int Height = 360;

    internal const string PngBase64 =
        "iVBORw0KGgoAAAANSUhEUgAAANQAAAFoCAYAAAAvodWiAAAGLUlEQVR42u3dyZFbNxCA4QlBGs1Kal9sLbakuTgEh6CTAnA8jkJH" +
        "heGsbFR5RheKw/fwAD4A/R2+Cw6sYnf/N1bx5J9vf/0LlHFiCNBhUJuzB7AaQYGgBIWgBIWgegtqm74UrEVQMGJQ2/MHwC1BgaBA" +
        "UCCow0E9BG4JCgQFggJBCQqOGNTj9CHA/wQFggJBgaAEBYKCToO6eAjcEhQICjoPyrBgeWiCAkFB40E9SY9AHkGBoEBQIChgUVCn" +
        "QCZBgaBAUBAwqMtTIJOgoGZQT9MjkEdQICgQFAgKEBQICgQFCAoEBYKCwEE9S49AHkFB1aCuToFMggJBgaAgYlCPgEyCAkGBoEBQ" +
        "wIKgnqdHII+gQFAgKBAUIChoJKjrR0AmQYGgQFAgKGBBUC/SI5BHUCAoEBQIChAUtBLUGZBJUCAoEBQEDGpzBmQSFNQM6mV6BPII" +
        "CgQFgqKAL3/+YQ6CYm40ucxPUCyMSFyColJE4hKUmEQlKPoJSViCEpKwBEU/MYnqSEG9So+U03JMd+ypHEEFj0lUtYPanlFATzH9" +
        "iMreFhOUmEQlKDGJqpugzllgjKDsMZegxCQqQQlKUIISk6gERcyYRCUoQQmqvaBep0fmGTko+51HUGISlaAEJShBCUpQgiJ2TKIS" +
        "lKAE1VBQj8+ZKFRQ9j2JoAQlKEEJSlCCEpSgBIWgBLUgqDfpkcMixXTH3g8TlKjEJChBCUpQghKUoBCUoAQlKEG1EtQFE8UKyr6n" +
        "EJSgBCUoUYlJUIISVMCgnlwwQ4ig7HkyQYlKTDWD+iU9Ms/IQdnvPIISlKAEJSoxCUpUYhIUgkJQohKToAQlKEExVFT2JyhRiUlQ" +
        "ohKToBgyKnuqGNSv6ZGyWo7JfsoSVOCo7OUYQT29oKImQrKHagQVKCxzF5SoxNR7UJesoE5E5npsghosLvMTFDNjMwdBgaAAQUE7" +
        "Qb1Nj0AeQYGgQFAgKEBQ0EhQzy6BTIICQYGgQFDAgqDepUcgj6BAUCAoEBQgqKMb8T927bVIUFdkGDMoe51LUGISlaDEJCpBiUlU" +
        "AYN6fsUEkWL6EZW9H7QT1Pv0yP0ixnTH/u8nKDGJSlBiEpWgxCQqQSEmUQlKUIISlJhEJSgxISpBiUlUghKTqAQlJlEJSkyIqkRQ" +
        "H9JjRCIoL+Id7Qb14iocx18xqmC3FD4oRy8qQQlKUIISk6hCBnUdgiNfI6rx7ypkUI5bVIISk6gEJSZiRRUmKEcsKkGJSVS9B/Vb" +
        "ehyJo23fSPc2dFCOVVSCEpSgBCUmRDVsUI5TVO0E9fK6a45ygKg6vr+hgnKMohKUmBgoqiGCcnyiEpSYGDCqroNybKJqPqjf02MP" +
        "HFk8PdyloBBU9KAcl6gEJSYCRNVVUI6J1qPqJihHRA9R/SSoTXMcD/ujautWmw/K0dBTVE0H5VjoLardoF5tmuBImB1VA3fbZFCO" +
        "g16j2gnqY3pcm8Mg19q321xQjoKeo2oqKMdA71E1E5QjYISomgjK8hklqtWDsnRGimrVoCyb0aJaLShLZsSoVgnKchk1qqMHZamM" +
        "HJWgEFTNoD6lx1osk1bUuvGjBWWJRIhqN6jXm+Isj2ajKnzr1YOyNCJFVTUoyyJaVNWCsiQiRvWToLaLWQ79RrXs9osHZSlEjqpo" +
        "UJZB9KgEBS0GZQmIqlBQho+o9gT1OT3OYeiMbk4Pi4IybERVKChDRlSFgjJcRFUoKENFVHOCerPdyzDhNqo9jUwOyhDhcFSCgmMH" +
        "ZXgwLaqDQRkaTI/q3qAMC+ZFtRPUTXq8ERPMdrMvKMOBPDtBGQosj+pETFDOiSGAoEBQIChAUCAoEBQgKBAUCAoEBQgKBAWCAgQF" +
        "ggJBgaAAQYGgQFCAoEBQICgQFCAoEBQIChAUCAoEBQgKBAWCAkEBggJBgaAAQYGgQFAgKEBQICgQFCAoEBQICgQFCAoEBYICBAWC" +
        "AkGBoAwCBAWBg/r+91dYjaBAUIJCUIJCUIICQYGgBIWgBAWCAkEJCkEJCkEJCgQFfhwLCAoEBYICBAWCAkGBoABBgaBAUICgQFAg" +
        "KBAUICgQFAgKEBQICgQFgjIEEBQICgQFCAoEBYICBAWCAkGBoABBwar+A7K4efHGEgjyAAAAAElFTkSuQmCC";
}
