<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Awake.WorldbookStudio.Web</RootNamespace>
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Awake.WorldbookStudio.Core\Awake.WorldbookStudio.Core.csproj" />
  </ItemGroup>
</Project>
