<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Awake.SdkSmoke</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GamePath Condition="'$(GamePath)' == ''">D:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord</GamePath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MarcusAIFramework" HintPath="$(MSBuildThisFileDirectory)..\MarcusAIFramework_Reference\SDK_20260815\ref\v1.3.15\MarcusAIFramework.dll" Private="true" />
    <Reference Include="MCMv5" HintPath="$(GamePath)\Modules\Bannerlord.MBOptionScreen\bin\Win64_Shipping_Client\MCMv5.dll" Private="true" />
    <Reference Include="Newtonsoft.Json" HintPath="$(GamePath)\bin\Win64_Shipping_Client\Newtonsoft.Json.dll" Private="true" />
    <Reference Include="TaleWorlds.CampaignSystem" HintPath="$(GamePath)\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll" Private="true" />
    <Reference Include="TaleWorlds.Core" HintPath="$(GamePath)\bin\Win64_Shipping_Client\TaleWorlds.Core.dll" Private="true" />
    <Reference Include="TaleWorlds.Library" HintPath="$(GamePath)\bin\Win64_Shipping_Client\TaleWorlds.Library.dll" Private="true" />
    <Reference Include="TaleWorlds.InputSystem" HintPath="$(GamePath)\bin\Win64_Shipping_Client\TaleWorlds.InputSystem.dll" Private="true" />
    <Reference Include="TaleWorlds.Localization" HintPath="$(GamePath)\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll" Private="true" />
    <Reference Include="TaleWorlds.ObjectSystem" HintPath="$(GamePath)\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll" Private="true" />
    <Compile Include="..\AWAKE\src\AwakeConfig.cs" Link="AwakeConfig.cs" />
    <Compile Include="..\AWAKE\src\AwakeConstants.cs" Link="AwakeConstants.cs" />
    <Compile Include="..\AWAKE\src\SceneDialogueSelection.cs" Link="SceneDialogueSelection.cs" />
    <Compile Include="..\AWAKE\src\SceneSelectionController.cs" Link="SceneSelectionController.cs" />
    <Compile Include="..\AWAKE\src\SceneDialoguePreviewMath.cs" Link="SceneDialoguePreviewMath.cs" />
    <Compile Include="..\AWAKE\src\SceneShoutAvailability.cs" Link="SceneShoutAvailability.cs" />
    <Compile Include="..\AWAKE\src\SceneDialogueModePolicy.cs" Link="SceneDialogueModePolicy.cs" />
    <Compile Include="..\AWAKE\src\SceneInputKeyMapper.cs" Link="SceneInputKeyMapper.cs" />
    <Compile Include="..\AWAKE\src\AwakeTranscriptModels.cs" Link="AwakeTranscriptModels.cs" />
    <Compile Include="..\AWAKE\src\AwakeTranscriptKeys.cs" Link="AwakeTranscriptKeys.cs" />
    <Compile Include="..\AWAKE\src\AwakeTranscriptService.cs" Link="AwakeTranscriptService.cs" />
    <Compile Include="..\AWAKE\src\AwakeTranscriptMigration.cs" Link="AwakeTranscriptMigration.cs" />
    <Compile Include="..\AWAKE\src\AwakeEventModels.cs" Link="AwakeEventModels.cs" />
    <Compile Include="..\AWAKE\src\AwakeEventEngineCore.cs" Link="AwakeEventEngineCore.cs" />
    <Compile Include="..\AWAKE\src\AwakeEventEffectRules.cs" Link="AwakeEventEffectRules.cs" />
    <Compile Include="..\AWAKE\src\AwakeUiDispatcher.cs" Link="AwakeUiDispatcher.cs" />
    <Compile Include="..\AWAKE\src\AwakeLocalization.cs" Link="AwakeLocalization.cs" />
    <Compile Include="..\AWAKE\src\ProbeExtension.cs" Link="ProbeExtension.cs" />
    <Compile Include="..\MarcusAIFramework_Reference\SDK_20260815\fake-host\FakeHost.cs" Link="FakeHost.cs" />
    <Compile Include="..\AWAKE\src\AwakeLog.cs" Link="AwakeLog.cs" />
    <Compile Include="..\AWAKE\src\AiTaskConstants.cs" Link="AiTaskConstants.cs" />
    <Compile Include="..\AWAKE\src\CloudExportPolicy.cs" Link="CloudExportPolicy.cs" />
    <Compile Include="..\AWAKE\src\AwakeDeveloperReport.cs" Link="AwakeDeveloperReport.cs" />
    <Compile Include="..\AWAKE\src\PermissionCatalog.cs" Link="PermissionCatalog.cs" />
    <Compile Include="..\AWAKE\src\PermissionGate.cs" Link="PermissionGate.cs" />
    <Compile Include="..\AWAKE\src\AiTaskGateway.cs" Link="AiTaskGateway.cs" />
    <Compile Include="..\AWAKE\src\CommandRiskPolicy.cs" Link="CommandRiskPolicy.cs" />
    <Compile Include="..\AWAKE\src\ContextProviders.cs" Link="ContextProviders.cs" />
    <Compile Include="..\AWAKE\src\WorldStateStore.cs" Link="WorldStateStore.cs" />
    <Compile Include="..\AWAKE\src\WorldCommandBridge.cs" Link="WorldCommandBridge.cs" />
    <Compile Include="..\AWAKE\src\AwakeWorldCommandAdapters.cs" Link="AwakeWorldCommandAdapters.cs" />
    <Compile Include="..\AWAKE\src\EventDialogueQueue.cs" Link="EventDialogueQueue.cs" />
    <Compile Include="..\AWAKE\src\NpcDialogueContext.cs" Link="NpcDialogueContext.cs" />
    <Compile Include="..\AWAKE\src\AwakeNpcTarget.cs" Link="AwakeNpcTarget.cs" />
    <Compile Include="..\AWAKE\src\AwakeUnnamedProfileService.cs" Link="AwakeUnnamedProfileService.cs" />
    <Compile Include="..\AWAKE\src\NpcDialogueConstants.cs" Link="NpcDialogueConstants.cs" />
    <Compile Include="..\AWAKE\src\NpcProactiveModels.cs" Link="NpcProactiveModels.cs" />
    <Compile Include="..\AWAKE\src\NpcProactiveService.cs" Link="NpcProactiveService.cs" />
    <Compile Include="..\AWAKE\src\NpcPromptTemplate.cs" Link="NpcPromptTemplate.cs" />
    <Compile Include="..\AWAKE\src\NpcDialogueOutput.cs" Link="NpcDialogueOutput.cs" />
    <Compile Include="..\AWAKE\src\NpcDialogueModels.cs" Link="NpcDialogueModels.cs" />
    <Compile Include="..\AWAKE\src\NpcDialogueReplyNormalizer.cs" Link="NpcDialogueReplyNormalizer.cs" />
    <Compile Include="..\AWAKE\src\NpcMemoryService.cs" Link="NpcMemoryService.cs" />
    <Compile Include="..\AWAKE\src\NpcMemoryOverviewBuilder.cs" Link="NpcMemoryOverviewBuilder.cs" />
    <Compile Include="..\AWAKE\src\AwakePerfProbe.cs" Link="AwakePerfProbe.cs" />
    <Compile Include="..\AWAKE\src\AwakeFeedback.cs" Link="AwakeFeedback.cs" />
    <Compile Include="..\AWAKE\src\AwakeMcmActions.cs" Link="AwakeMcmActions.cs" />
    <Compile Include="..\AWAKE\src\AwakePresetCatalog.cs" Link="AwakePresetCatalog.cs" />
    <Compile Include="..\AWAKE\src\AwakeMessengerHistory.cs" Link="AwakeMessengerHistory.cs" />
    <Compile Include="..\AWAKE\src\AwakeBackgroundTask.cs" Link="AwakeBackgroundTask.cs" />
    <Compile Include="..\AWAKE\src\AwakeRuleRegistry.cs" Link="AwakeRuleRegistry.cs" />
    <Compile Include="..\AWAKE\src\AwakeEventDataLoader.cs" Link="AwakeEventDataLoader.cs" />
    <Compile Include="..\AWAKE\src\NpcMemoryConsolidator.cs" Link="NpcMemoryConsolidator.cs" />
    <Compile Include="..\AWAKE\src\NpcProactiveMotiveRegistry.cs" Link="NpcProactiveMotiveRegistry.cs" />
    <Compile Include="..\AWAKE\src\AwakeContentApi.cs" Link="AwakeContentApi.cs" />
    <Compile Include="..\AWAKE\src\AwakeDialogueSessionCoordinator.cs" Link="AwakeDialogueSessionCoordinator.cs" />
    <Compile Include="..\AWAKE\src\AwakeOnboardingService.cs" Link="AwakeOnboardingService.cs" />
    <Compile Include="..\AWAKE\src\AwakeStorageContract.cs" Link="AwakeStorageContract.cs" />
    <Compile Include="..\AWAKE\src\AwakeMarcusLinkService.cs" Link="AwakeMarcusLinkService.cs" />
    <Compile Include="..\AWAKE\src\NpcDialoguePromptPipeline.cs" Link="NpcDialoguePromptPipeline.cs" />
    <Compile Include="..\AWAKE\src\WorldEventLedger.cs" Link="WorldEventLedger.cs" />
    <Compile Include="..\AWAKE\src\WorldEventInboxFormatter.cs" Link="WorldEventInboxFormatter.cs" />
    <Compile Include="..\AWAKE\src\NarrativeReportBuilder.cs" Link="NarrativeReportBuilder.cs" />
    <Compile Include="..\AWAKE\src\AwakeRuntime.cs" Link="AwakeRuntime.cs" />
    <Compile Include="..\AWAKE\src\KnowledgeModels.cs" Link="KnowledgeModels.cs" />
    <Compile Include="..\AWAKE\src\KnowledgeService.cs" Link="KnowledgeService.cs" />
    <Compile Include="..\AWAKE\src\KnowledgeRuntime.cs" Link="KnowledgeRuntime.cs" />
    <Compile Include="..\AWAKE\src\WorldbookModels.cs" Link="WorldbookModels.cs" />
    <Compile Include="..\AWAKE\src\WorldbookLoader.cs" Link="WorldbookLoader.cs" />
    <Compile Include="..\AWAKE\src\WorldbookService.cs" Link="WorldbookService.cs" />
    <Compile Include="..\AWAKE\src\WorldbookRuntime.cs" Link="WorldbookRuntime.cs" />
    <Compile Include="..\AWAKE\src\WorldbookTextMappingResolver.cs" Link="WorldbookTextMappingResolver.cs" />
    <Compile Include="..\MarcusAIFramework_Reference\SDK_20260815\test-kit\MafAssertions.cs" Link="MafAssertions.cs" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>
